all:
	echo "Spin all things from here"
	pwd
	cd ch01 && pwd && $(MAKE) all && pwd
	pwd

test:
	echo "Spin tests from here"
	pwd
	cd ch01 && pwd && $(MAKE) test && pwd
	pwd

clean:
	cd ch01 && pwd && $(MAKE) clean && pwd
